### ISSUE TITLE
Provide a mean to reproduce benchmarks results

### ISSUE THREAD

**Issue by erebe** [zegelin/cassandra-exporter#11]
Hello,

I am the author of criteo/cassandra_exporter and I would like to be able to reproduce your benchmarks in order to understand where are coming from the differences in performance from the other exporters you compare.

On my side, even on a pretty loaded cluster with a lot of keyspaces/tables the scraping time does not take more than 9sec (the machines have big cpus). But even while when I switched from jmx_exporter, I haven't noticed a huge performance drop regarding the scrapping time. So I am a bit concerned on how you end-up with those results.

Can you please provide a mean to reproduce your benchmarks and the config you are running them on ?

Thanks in advance :)

**Comment by zegelin** [comment]
Closing this as I'm migrating issues to the Instaclustr repo.
Issue duplicated at https://github.com/instaclustr/cassandra-exporter/issues/3
